### ISSUE TITLE
[Bug]: rules_esbuild_dependencies fails with 0.14.0

### ISSUE THREAD

**Issue by mrmeku** [aspect-build/rules_esbuild#125]
### What happened?

When upgrading from 0.13.6 to 0.14.0 the following error is produced

```
ERROR: Traceback (most recent call last):
        File "/usr/local/home/mrmeku/depot/src/stairwell/WORKSPACE", line 786, column 28, in <toplevel>
                esbuild_register_toolchains(
        File "/usr/local/home/mrmeku/.cache/bazel/_bazel_mrmeku/0fd53cc9eeb7aea8d7b8b30c5522fa8c/external/aspect_rules_esbuild/esbuild/repositories.bzl", line 116, column 15, in esbuild_register_toolchains
                npm_import(
        File "/usr/local/home/mrmeku/.cache/bazel/_bazel_mrmeku/0fd53cc9eeb7aea8d7b8b30c5522fa8c/external/aspect_rules_js/npm/npm_import.bzl", line 631, column 13, in npm_import
                fail(msg)
Error in fail: Invalid npm_import parameter 'register_copy_directory_toolchains'
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
Just try to build anything which depends on the esbuild toolchain to trigger the error
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
You `aspect_bazel_lib` dependency likely needs to be updated to the latest as well. This rule set has a transitive dependency on that one.
