### ISSUE TITLE
Incompatible with current rules_js

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_esbuild#15]
When trying to use this ruleset with current (https://github.com/aspect-build/rules_js/commit/61b1867c79e6ee46a0a926fd9b6894e95457c01b) rules_js, I receive the following error:

```
ERROR: Traceback (most recent call last):
	File "/Users/john/figma/figma/WORKSPACE.bazel", line 120, column 28, in <toplevel>
		esbuild_register_toolchains(
	File "/private/var/tmp/_bazel_johnfirebaugh/67beefda950d56283b98d96980e6e332/external/aspect_rules_esbuild/esbuild/repositories.bzl", line 100, column 15, in esbuild_register_toolchains
		npm_import(
	File "/private/var/tmp/_bazel_johnfirebaugh/67beefda950d56283b98d96980e6e332/external/aspect_rules_js/js/npm_import.bzl", line 32, column 5, in npm_import
		def npm_import(
Error: npm_import() got unexpected keyword argument: enable_lifecycle_hooks
```

**Comment by jfirebaugh** [comment]
Looks like this will be fixed by https://github.com/aspect-build/rules_esbuild/pull/14.

**Comment by alexeagle** [comment]
should be fixed at HEAD, could you try again? 🙏🏻

**Comment by jfirebaugh** [comment]
Confirmed, thank you!
